package com.example.cwlgd.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.cwl.entity.Comic;
import com.example.cwl.entity.db.DBChapters;
import com.example.cwl.entity.db.DBSearchResult;

import com.example.cwlgd.greendao.ComicDao;
import com.example.cwlgd.greendao.DBChaptersDao;
import com.example.cwlgd.greendao.DBSearchResultDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig comicDaoConfig;
    private final DaoConfig dBChaptersDaoConfig;
    private final DaoConfig dBSearchResultDaoConfig;

    private final ComicDao comicDao;
    private final DBChaptersDao dBChaptersDao;
    private final DBSearchResultDao dBSearchResultDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        comicDaoConfig = daoConfigMap.get(ComicDao.class).clone();
        comicDaoConfig.initIdentityScope(type);

        dBChaptersDaoConfig = daoConfigMap.get(DBChaptersDao.class).clone();
        dBChaptersDaoConfig.initIdentityScope(type);

        dBSearchResultDaoConfig = daoConfigMap.get(DBSearchResultDao.class).clone();
        dBSearchResultDaoConfig.initIdentityScope(type);

        comicDao = new ComicDao(comicDaoConfig, this);
        dBChaptersDao = new DBChaptersDao(dBChaptersDaoConfig, this);
        dBSearchResultDao = new DBSearchResultDao(dBSearchResultDaoConfig, this);

        registerDao(Comic.class, comicDao);
        registerDao(DBChapters.class, dBChaptersDao);
        registerDao(DBSearchResult.class, dBSearchResultDao);
    }
    
    public void clear() {
        comicDaoConfig.getIdentityScope().clear();
        dBChaptersDaoConfig.getIdentityScope().clear();
        dBSearchResultDaoConfig.getIdentityScope().clear();
    }

    public ComicDao getComicDao() {
        return comicDao;
    }

    public DBChaptersDao getDBChaptersDao() {
        return dBChaptersDao;
    }

    public DBSearchResultDao getDBSearchResultDao() {
        return dBSearchResultDao;
    }

}
